name: Specmatic Contract Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  specmatic-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Install Maven
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    # Step 4: Build and run the Spring Boot application
    - name: Build and Run Spring Boot Application
      run: |
        mvn clean install -DskipTests
        nohup java -jar target/*.jar &
        sleep 30 # Give the server time to start

    # Step 5: Install Specmatic CLI
    - name: Install Specmatic
      run: |
        curl -L https://github.com/znsio/specmatic/releases/latest/download/specmatic.jar --output specmatic.jar

    # Step 6: Run Specmatic Contract Tests
    - name: Run Specmatic Contract Tests
      run: |
        java -jar specmatic.jar test \
          --contract=./contracts/products_api.yaml \
          --host=localhost \
          --port=8080
